# HTTP 连接配置 T0D0
ok:
  http:
    connect-timeout: 30
    keep-alive-duration: 300
    max-idle-connections: 200
    read-timeout: 30
    write-timeout: 30

# 腾讯云账号相关的信息配置 TODO
#tencent:
#  sms:
#    account:
#      secret-id:
#      secret-key:
#      sign_name:
#      sms-sdk-app-id:
#      template-id:


# 数据库相关的信息配置 TODO
spring:
  datasource:
    url: jdbc:mysql://39.106.50.18:3306/austin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # kafka相关的信息配置 TODO
#  kafka:
#    bootstrap-servers:
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto:
#        offset:
#          reset: earliest

# tomcat / HikariPool(数据库连接池 配置） TODO
# 消息topicName TODO
#austin:
#  topic:
#    name: austin

mybatis:
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
